### PR TITLE
PurgeTSS docs for Alloy integration

### PR DESCRIPTION
**Pull request by caspahouzer**
Here are the docs for [this PR](https://github.com/tidev/alloy/pull/1323)

I integrated all docs from https://github.com/macCesar/purgeTSS, extended and changed to follow our doc guidelines.

This PR may not be approved until [this PR](https://github.com/tidev/alloy/pull/1323) is completely merged

### CODE REVIEW

**Comment by m1ga** [comment]
wouldn't it be better to link to https://github.com/macCesar/purgeTSS/releases in "whats new" and not include all the changelogs into titanium-docs? Otherwise we always have to create a new page when purgetss gets an update

**Comment by cb1kenobi** [comment]
Agree with @m1ga, let's keep PurgeTSS release notes in PurgeTSS repo.

**Comment by caspahouzer** [comment]
> wouldn't it be better to link to https://github.com/macCesar/purgeTSS/releases in "whats new" and not include all the changelogs into titanium-docs? Otherwise we always have to create a new page when purgetss gets an update

Yes. It' so much less work.

Bildschirmfoto 2022-03-30 um 07 16 48

**Comment by caspahouzer** [comment]
removed nearly all readme in favor of official [https://purgetss.com/](https://purgetss.com/) docs

Bildschirmfoto 2022-04-18 um 08 39 07

**Comment by caspahouzer** [comment]
I've finished this PR. It's ready to merge as `alloy 2.0.0` is released

**Review by cb1kenobi — APPROVED** [review]
**APPROVED**

**Pull request merged**
