### PR TITLE
darkMode with variables

### PR DESCRIPTION
**Pull request by m1ga**
This needs to be merged first: https://github.com/tidev/docs-devkit/pull/215

This will make the dark/light mode switchable.

### CODE REVIEW

**Comment by caspahouzer** [comment]
I found this one: https://www.freecodecamp.org/news/how-to-build-a-dark-mode-switcher-with-tailwind-css-and-flowbite/

**Comment by caspahouzer** [comment]
i have been working with vuepress more and more in the last few days and am now relatively familiar with it.

**Comment by m1ga** [comment]
> I found this one: https://www.freecodecamp.org/news/how-to-build-a-dark-mode-switcher-with-tailwind-css-and-flowbite/

then we have to rebuild the whole header section, don't want to do that :smile: I have it almost running with just a few additions and not another npm package :)

**Comment by m1ga** [comment]
Working when https://github.com/tidev/docs-devkit/pull/215 is merged

**Comment by caspahouzer** [comment]
Could you also style the search?

image

**Comment by m1ga** [comment]
good catch!

Screenshot_20220522_121126

**Pull request merged**
