### PR TITLE
Order api list

### LINKED ISSUE #11: Sort side menu alphabetically
Site: https://appcelerator.github.io/titanium-docs/api/

I think it would be a bit better for the usability to sort the left side menu alphabetically. Modules can be at the last place but then add a border-top to it so it is a bit separated from the other list.

### PR DESCRIPTION
**Pull request by m1ga**
Would fixes #11 

Looking at the spacing it looks like items without links (just a `<p>`) have a bigger spacing. Setting
```css
.sidebar a {
    display: block;
}
```
would fix that but I'm not sure where :smile:

### CODE REVIEW

**Comment by janvennemann** [comment]
My initial idea for this sorting was to have more frequently used APIs at the top for faster navigation. That's why stuff like UI, App, I/O or Network are at the top. But i understand this might be confusing since it seems totally random if you expect alphabetically sorted items like in the old docs.

Maybe we can have both by using alphabetically sorted list in the navigation bar and make better use of the now pretty much empty API docs root page. Instead of the warning alert i imagine a nice overview of the most frequently used modules there.

**Comment by m1ga** [comment]
Perhaps  a list of important links at https://appcelerator.github.io/titanium-docs/api/ in the main section (below the warning). Since it is called `Ti.UI.` in Titanium it's difficult to find `User Interface` :smile: 
Or use two menus: one with the `Ti.UI..` syntax and the other one with "nice" names

**Comment by janvennemann** [comment]
> Perhaps a list of important links at https://appcelerator.github.io/titanium-docs/api/ in the main section (below the warning).

Yes, that's exactly what i have in mind!

> Since it is called `Ti.UI.` in Titanium it's difficult to find `User Interface` 😄 
> Or use two menus: one with the `Ti.UI..` syntax and the other one with "nice" names

Yeah, it was not like that at first. `User Interface` used to be just the group header and wouldn't link to any page when you clicked it (it would just open the group). We made some changes recently and now it directly links to `Ti.UI` which IMHO is not ideal.

I'll give this a closer look soon to see if it works well with the additional list in the main content area.

**Comment by sgtcoolguy** [comment]
I figured I'd start with @m1ga 's suggestion and just run with it for now. I've re-ordered the sidebar to be hierarchical and just reflect the API namespaces/hierarchy in an alphabetical order. The initial `/titanium-docs/api` page now has the "experimental" warning removed and I've added an overview with some manual grouping of the APIs by category.

**Comment by m1ga** [comment]
Nice! Could you change it so that a click on the name "Titanium" will load the page AND open the drop-down? So like clicking on the white-space

**Pull request closed without merging**
