### PR TITLE
Remove some more studio stuff

### PR DESCRIPTION
**Pull request by m1ga**
Still a lot of Studio stuff left but I removed some

### CODE REVIEW

**Comment by caspahouzer** [comment]
Did you build the `guide.json` automatically with `node ./scripts/generate-guides` ?

**Comment by m1ga** [comment]
I've rerun it again. Just changed the order so should be fine now. Thanks for the hint!

**Review by caspahouzer — APPROVED** [review]
LGTM **APPROVED**

**Review by caspahouzer — APPROVED** [review]
guide.json build automatically **APPROVED**

**Pull request merged**
