### PR TITLE
re-commit of api.json due to vscode formatting

### PR DESCRIPTION
**Pull request by caspahouzer**
@hansemannn this is the corrected formatting

I took this [file](https://raw.githubusercontent.com/caspahouzer/titanium-docs/8e206352ddd60dc4615d6ed7cfa9e9c838b976da/docs/.vuepress/api.json) and disabled formatting before making changes

### CODE REVIEW

**Comment by hansemannn** [comment]
Something is wrong again now, you deleted > 300.000 lines of code. Please restore the old api.json and only apply the changes, thx!

**Comment by caspahouzer** [comment]
I really don’t know what happened. 

I’ll have a look into that tomorrow

**Comment by caspahouzer** [comment]
@hansemannn I'm sorry for this shitty PR. I'take more care about that next time. Hopefully, everything's okay now

**Comment by hansemannn** [comment]
No worries, we are all learning! :)

**Pull request closed without merging**
