### PR TITLE
docs: add 12.6.0.RC release notes

### PR DESCRIPTION
**Pull request by hansemannn**
Related to https://github.com/tidev/tidev-www/pull/50

### CODE REVIEW

**Comment by cb1kenobi** [comment]
Revert not needed anymore :)

**Comment by hansemannn** [comment]
This was the revert of the revert

**Comment by hansemannn** [comment]
@cb1kenobi I still don't understand why this was closed. It was the revert of the revert - right now, no 12.6.0 docs are merged.

**Comment by cb1kenobi** [comment]
Oh, sorry @hansemannn I was confused. I didn't see there was already a revert. I thought this PR reverted #231. But now I see #232 reverted #231 and this PR reverts #232. Let's reopen this and merge it.

**Pull request merged**
