### PR TITLE
docs: added missing OptionBar navigation

### PR DESCRIPTION
**Pull request by caspahouzer**
https://github.com/tidev/titanium-docs/issues/94

### CODE REVIEW

**Comment by m1ga** [comment]
Can't you disable the "format on save" option in your editor :smile: It makes it really hard to find the one changed line.

**Edit:** but it is consistent and we can keep it as long as it stays like this the next time :+1:

**Comment by caspahouzer** [comment]
I will disable vscode format on save next time working in tidev projects

**Comment by m1ga** [comment]
Since the whole file is consistent its fine. 
The other PR just changed e.g. Tabs -> Spaces in some lines. Here it kept the tabs which is good :smile:

**Comment by m1ga** [comment]
Screenshot_20220326_121729

Menu entry is there, fine for me :+1:

**Review by m1ga — APPROVED** [review]

**Comment by caspahouzer** [comment]
Merged 👍🏻

**Comment by hansemannn** [comment]
This should not have been merged. The format was correct as-is and follows the appc-format guidelines.

**Pull request merged**
