### PR TITLE
feat: add docs for the new iOS 17+ privacy requirements

### PR DESCRIPTION
**Pull request by hansemannn**
Details for the new iOS 17+ privacy requirements. More changes [here](https://github.com/tidev/titanium-sdk/pull/14007).

### CODE REVIEW

**Review by m1ga — APPROVED** [review]
LGTM

**Comment by hansemannn** [comment]
@m1ga Have you also been able to submit a build?

**Comment by m1ga** [comment]
no, I've only checked the text :smile: didn't do any tests with an app. I can test a Testflight build tomorrow to see if I get the warnings

**Comment by m1ga** [comment]
just pushed a 12.3.0 app (without any changes or privacy file) to the testflight and I don't get the warnings :shrug: So I can't test it

**Comment by hansemannn** [comment]
Same here currently with our main app that reproduced it last week. Maybe Apple only sends email for some devs so far to reduce noise. We can keep it open until it get's more concrete, as Titanium devs can already place the file to be sure.

**Comment by m1ga** [comment]
as there are more people asking for this now: should we merge the docs so I can link them to the article instead of pointing to this PR all the time?

**Comment by m1ga** [comment]
Thanks :+1: 

Looks like it doesn't like the link to the file: https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/PrivacyInfo.xcprivacy

Should we add inlince code to display the file as a workaround?

**Pull request merged**
